config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'tasks#index'
  get 'tasks/new', to: 'tasks#new', as: 'new'
  get 'tasks/:id', to: 'tasks#show', as: 'id'
  post 'tasks', to: 'tasks#create'
  get 'tasks/:id/edit', to: 'tasks#edit', as: 'edit'
  patch 'tasks/:id', to: 'tasks#update', as: 'update'
  delete 'tasks/:id/destroy', to: 'tasks#destroy', as: 'destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @id = params[:id]
    @task = Task.find(@id)
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to root_path
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to id_path(@task)
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to root_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/task_helper.rb
module TaskHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
    <%= javascript_importmap_tags %>
  </head>

  <body class= 'container jusify-content-center'>
    <h1>💼 Task manager 💼</h1>
    <br>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<%= form_with url: update_path, model: @task do |f|%>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details, size: "35x10" %>
  <%= f.label :completed %>
  <%= f.check_box :completed %>
  <%= f.submit "Update" %>
<% end %>

app/views/tasks/index.html.erb
<div class="justify-content-center">
  <h2>My Tasks</h2>
  <br>
  <ul class="list-group">
    <% @tasks.each do |task| %>
      <li class="list-group-item">
        <% if task. completed %>
        <i class="fa-regular fa-square-check"></i>
        <% else %>
        <i class="fa-regular fa-square"></i>
        <% end %>
        - <%= link_to "#{task.title}", id_path(task.id) %>
        <%= link_to raw("<i class='fa-regular fa-trash-can'></i>"), destroy_path(task.id), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
      </li>
    <% end %>
  </ul>
  <br>
  <%= link_to "Add a new task", new_path, class: 'btn btn-primary' %>
</div>

app/views/tasks/new.html.erb
<%= form_with model: @task do |f|%>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details, size: "35x10" %>
  <%= f.label :completed %>
  <%= f.check_box :completed %>
  <%= f.submit "New task" %>
<% end %>

app/views/tasks/show.html.erb
<div class="justify-content-center">
  <div class="d-flex p-3 m-3">
    <h3><%= @task.title %></h3>
    <%= link_to 'Edit', edit_path, class: "btn btn-outline-secondary" %>
  </div>
  <h5><%= @task.details %></h5>
  <% if @task.completed %>
  <p>✔️ Task completed!</p>
  <% else %>
  <p>❌ This task is not completed yet!</p>
  <% end %>

  <%= link_to "back to index", root_path, class: "btn btn-primary" %>
</div>